package com.PartyApi.Payloads;

public class PartyApiSitPayloads {
	
	public static final String PersonIndentificationBasic = "{\n"
			+ "  \"identityType\": \"NationalIdentityNumber\",\n"
			+ "  \"externalReference\": \"PascalTest\",\n"
			+ "  \"billingReference\": \"Test123\",\n"
			+ "  \"identificationReason\": \"Claims\",\n"
			+ "  \"maxCacheAge\": \"0\",\n"
			+ "  \"identificationType\": \"Basic\",\n"
			+ "  \"businessUnit\": \"Life\",\n"
			+ "  \"channel\": \"Branch\"\n"
			+ "}";
	
	public static final String PersonIndentificationEnhanced = "{\n"
			+ "  \"identityType\": \"NationalIdentityNumber\",\n"
			+ "  \"externalReference\": \"Pascal12\",\n"
			+ "  \"billingReference\": \"Test123\",\n"
			+ "  \"identificationReason\": \"Claims\",\n"
			+ "  \"maxCacheAge\": \"0\",\n"
			+ "  \"identificationType\": \"Enhanced\",\n"
			+ "  \"businessUnit\": \"Life\",\n"
			+ "  \"channel\": \"Branch\"\n"
			+ "}";
	
	public static final String PersonIndentificationWCMI = "{\n"
			+ "  \"identityType\": \"NationalIdentityNumber\",\n"
			+ "  \"externalReference\": \"Pascal12\",\n"
			+ "  \"billingReference\": \"Test123\",\n"
			+ "  \"identificationReason\": \"Claims\",\n"
			+ "  \"maxCacheAge\": \"0\",\n"
			+ "  \"identificationType\": \"Enhanced\",\n"
			+ "  \"businessUnit\": \"Life\",\n"
			+ "  \"channel\": \"Branch\"\n"
			+ "}";
	

	
	public static final String PersonIndentificationWCMI2 = "	{\n"
			+ "		  \"identityType\": \"NationalIdentityNumber\",\n"
			+ "		  \"externalReference\": \"Pascal12\",\n"
			+ "		  \"billingReference\": \"Test123\",\n"
			+ "		  \"identificationReason\": \"Claims\",\n"
			+ "		  \"maxCacheAge\": \"0\",\n"
			+ "		  \"identificationType\": \"Enhanced\",\n"
			+ "		  \"businessUnit\": \"Life\",\n"
			+ "		  \"channel\": \"Branch\"\n"
			+ "		}";

	public static final String PersonVerificationRRLowPassport = "{\n"
			+ "\"identityType\": \"Passport\",\n"
			+ "\"firstNames\": \"Pascal\",\n"
			+ "\"surname\": \"Masinga\",\n"
			+ "\"birthDate\": \"1993-06-11\",\n"
			+ "\"sourceOfIncome\": \"None\",\n"
			+ "\"sourceOfWealth\": \"None\",\n"
			+ "\"Address\": {\n"
			+ "\"AddressType\": \"Street\",\n"
			+ "\"AddressString\": \"4 Gayle Road, Morganridge, Boksburg, 1459\",\n"
			+ "\"AddressLine1\": \"4 Gayle Road\",\n"
			+ "\"AddressLine2\": \"Morganridge\",\n"
			+ "\"AddressLine3\": \"Boksburg\",\n"
			+ "\"Suburb\": \"Morganridge\",\n"
			+ "\"TownCity\": \"Boksburg\",\n"
			+ "\"ProvinceState\": \"Gauteng\",\n"
			+ "\"Country\": \"South Africa\",\n"
			+ "\"PostalZipCode\": \"1459\"\n"
			+ "    },\n"
			+ "\"verificationReason\": \"None\",\n"
			+ "\"annualisedPremium\": \"8000.00\",\n"
			+ "\"productType\": \"FuneralWithRiders\",\n"
			+ "\"premiumCollectionMethod\": \"Cash\",\n"
			+ "\"verifyRequirements\": false,\n"
			+ "\"businessUnit\": \"Life\",\n"
			+ "\"channel\": \"Branch\",\n"
			+ "\"externalReference\": \"MyRef123\",\n"
			+ "\"billingReference\": \"MyRef456\",\n"
			+ "\"maxCacheAge\": \"0\"\n"
			+ "}\n"
			+ "\n"
			+ "";
	
	public static final String PersonVerificationRRHighPassport = "{\n"
			+ "\"identityType\": \"Passport\",\n"
			+ "\"firstNames\":\"MANTE REGINAH\",\n"
			+ "\"surname\": \"MASHABELA\",\n"
			+ "\"birthDate\": \"1976-06-06T08:47:19.361Z\",\n"
			+ "\"sourceOfIncome\": \"None\",\n"
			+ "\"sourceOfWealth\": \"None\",\n"
			+ "\"Address\": {\n"
			+ "\"AddressType\": \"Street\",\n"
			+ "\"AddressString\": \"4 Gayle Road, Morganridge, Boksburg, 1459\",\n"
			+ "\"AddressLine1\": \"4 Gayle Road\",\n"
			+ "\"AddressLine2\": \"Morganridge\",\n"
			+ "\"AddressLine3\": \"Boksburg\",\n"
			+ "\"Suburb\": \"Morganridge\",\n"
			+ "\"TownCity\": \"Boksburg\",\n"
			+ "\"ProvinceState\": \"Gauteng\",\n"
			+ "\"Country\": \"South Africa\",\n"
			+ "\"PostalZipCode\": \"1459\"\n"
			+ "    },\n"
			+ "\"verificationReason\": \"None\",\n"
			+ "\"annualisedPremium\": \"8000.00\",\n"
			+ "\"productType\": \"FuneralWithRiders\",\n"
			+ "\"premiumCollectionMethod\": \"Cash\",\n"
			+ "\"verifyRequirements\": true,\n"
			+ "\"businessUnit\": \"Life\",\n"
			+ "\"channel\": \"Branch\",\n"
			+ "\"externalReference\": \"MyRef123\",\n"
			+ "\"billingReference\": \"MyRef456\",\n"
			+ "\"maxCacheAge\": \"0\"\n"
			+ "}\n"
			+ "\n"
			+ "";
	
	public static final String PersonVerificationRRLowID = "{\n"
			+ "\"identityType\": \"NationalIdentityNumber\",\n"
			+ "\"firstNames\": \"Pascal\",\n"
			+ "\"surname\": \"Masinga\",\n"
			+ "\"sourceOfIncome\": \"None\",\n"
			+ "\"sourceOfWealth\": \"None\",\n"
			+ "\"Address\": {\n"
			+ "\"AddressType\": \"Street\",\n"
			+ "\"AddressString\": \"4 Gayle Road, Morganridge, Boksburg, 1459\",\n"
			+ "\"AddressLine1\": \"4 Gayle Road\",\n"
			+ "\"AddressLine2\": \"Morganridge\",\n"
			+ "\"AddressLine3\": \"Boksburg\",\n"
			+ "\"Suburb\": \"Morganridge\",\n"
			+ "\"TownCity\": \"Boksburg\",\n"
			+ "\"ProvinceState\": \"Gauteng\",\n"
			+ "\"Country\": \"South Africa\",\n"
			+ "\"PostalZipCode\": \"1459\"\n"
			+ "    },\n"
			+ "\"verificationReason\": \"None\",\n"
			+ "\"annualisedPremium\": \"8000.00\",\n"
			+ "\"productType\": \"Life\",\n"
			+ "\"premiumCollectionMethod\": \"Cash\",\n"
			+ "\"verifyRequirements\": true,\n"
			+ "\"businessUnit\": \"Life\",\n"
			+ "\"channel\": \"Branch\",\n"
			+ "\"externalReference\": \"MyRef123\",\n"
			+ "\"billingReference\": \"MyRef456\",\n"
			+ "\"maxCacheAge\": \"0\"\n"
			+ "}\n"
			+ "";
	
	public static final String PersonVerificationRRLowID2 = "{\n"
			+ "\"identityType\": \"NationalIdentityNumber\",\n"
			+ "\"firstNames\": \"Pascal\",\n"
			+ "\"surname\": \"Masinga\",\n"
			+ "\"sourceOfIncome\": \"None\",\n"
			+ "\"sourceOfWealth\": \"None\",\n"
			+ "\"Address\": {\n"
			+ "\"AddressType\": \"Street\",\n"
			+ "\"AddressString\": \"4 Gayle Road, Morganridge, Boksburg, 1459\",\n"
			+ "\"AddressLine1\": \"4 Gayle Road\",\n"
			+ "\"AddressLine2\": \"Morganridge\",\n"
			+ "\"AddressLine3\": \"Boksburg\",\n"
			+ "\"Suburb\": \"Morganridge\",\n"
			+ "\"TownCity\": \"Boksburg\",\n"
			+ "\"ProvinceState\": \"Gauteng\",\n"
			+ "\"Country\": \"South Africa\",\n"
			+ "\"PostalZipCode\": \"1459\"\n"
			+ "    },\n"
			+ "\"verificationReason\": \"None\",\n"
			+ "\"annualisedPremium\": \"8000.00\",\n"
			+ "\"productType\": \"Life\",\n"
			+ "\"premiumCollectionMethod\": \"Cash\",\n"
			+ "\"verifyRequirements\": true,\n"
			+ "\"businessUnit\": \"Life\",\n"
			+ "\"channel\": \"Branch\",\n"
			+ "\"externalReference\": \"MyRef123\",\n"
			+ "\"billingReference\": \"MyRef456\",\n"
			+ "\"maxCacheAge\": \"0\"\n"
			+ "}\n"
			+ "";
	
	public static final String PersonVerificationRRHighID = "{\n"
			+ "\"identityType\": \"NationalIdentityNumber\",\n"
			+ "\"firstNames\": \"Test\",\n"
			+ "\"surname\": \"Test\",\n"
			+ "\"sourceOfIncome\": \"None\",\n"
			+ "\"sourceOfWealth\": \"None\",\n"
			+ "\"Address\": {\n"
			+ "\"AddressType\": \"Street\",\n"
			+ "\"AddressString\": \"4 Gayle Road, Morganridge, Boksburg, 1459\",\n"
			+ "\"AddressLine1\": \"4 Gayle Road\",\n"
			+ "\"AddressLine2\": \"Morganridge\",\n"
			+ "\"AddressLine3\": \"Boksburg\",\n"
			+ "\"Suburb\": \"Morganridge\",\n"
			+ "\"TownCity\": \"Boksburg\",\n"
			+ "\"ProvinceState\": \"Gauteng\",\n"
			+ "\"Country\": \"South Africa\",\n"
			+ "\"PostalZipCode\": \"1459\"\n"
			+ "    },\n"
			+ "\"verificationReason\": \"None\",\n"
			+ "\"annualisedPremium\": \"8000.00\",\n"
			+ "\"productType\": \"FuneralWithRiders\",\n"
			+ "\"premiumCollectionMethod\": \"Cash\",\n"
			+ "\"verifyRequirements\": false,\n"
			+ "\"businessUnit\": \"Life\",\n"
			+ "\"channel\": \"Branch\",\n"
			+ "\"externalReference\": \"MyRef123\",\n"
			+ "\"billingReference\": \"MyRef456\",\n"
			+ "\"maxCacheAge\": \"0\"\n"
			+ "}";
}
