package com.policyPayloads;

public class policyPayloads {

	

	public static final String UpdateBankAccountAndDebitDayPatload=
			"{\r\n"
			+ "    \"$type\": \"DebitOrder\",\r\n"
			+ "    \"bankAccount\": {\r\n"
			+ "        \"accountHolderName\": \"ZenziDlangamandla\",\r\n"
			+ "        \"accountType\": \"Cheque\",\r\n"
			+ "        \"bankName\": \"TymeBank\",\r\n"
			+ "        \"branchCode\": \"678910\",\r\n"
			+ "        \"accountNumber\": \"51024594455\"\r\n"
			+ "    },\r\n"
			+ "    \"debitDay\": \"18\",\r\n"
			+ "    \"collectionMethod\": \"DebitOrder\",\r\n"
			+ "    \"policyPayer\": {\r\n"
			+ "        \"$type\": \"PolicyPayer\",\r\n"
			+ "        \"preferedCommunicationMethod\": \"None\",\r\n"
			+ "        \"addresses\": [],\r\n"
			+ "        \"emailAddress\": \"Testcase@Gmail.Com\",\r\n"
			+ "        \"language\": \"None\",\r\n"
			+ "        \"sourceOfIncome\": \"None\",\r\n"
			+ "        \"sourceOfWealth\": \"None\",\r\n"
			+ "        \"countryOfResidence\": \"None\",\r\n"
			+ "        \"requirements\": [],\r\n"
			+ "        \"verifications\": [],\r\n"
			+ "        \"documents\": [],\r\n"
			+ "        \"title\": \"None\",\r\n"
			+ "        \"initials\": \"Z\",\r\n"
			+ "        \"firstNames\": \"Zenzi\",\r\n"
			+ "        \"surname\": \"Dlangamandla\",\r\n"
			+ "        \"gender\": \"None\",\r\n"
			+ "        \"birthDate\": \"1984-12-26T00:00:00+00:00\",\r\n"
			+ "        \"identities\": [\r\n"
			+ "            {\r\n"
			+ "                \"identityType\": \"NationalIdentityNumber\",\r\n"
			+ "                \"identityNumber\": \"8412260245088\",\r\n"
			+ "                \"issueCountry\": \"None\",\r\n"
			+ "                \"citizenshipCountry\": \"SouthAfrica\"\r\n"
			+ "            }\r\n"
			+ "        ],\r\n"
			+ "        \"maritalStatus\": \"None\",\r\n"
			+ "        \"contactNumbers\": [\r\n"
			+ "            {\r\n"
			+ "                \"contactType\": \"Mobile\",\r\n"
			+ "                \"contactNumber\": \"0820720777\",\r\n"
			+ "                \"countryCode\": \"27\"\r\n"
			+ "            }\r\n"
			+ "        ],\r\n"
			+ "        \"partyType\": \"Person\",\r\n"
			+ "        \"rolePlayerType\": \"PolicyPayer\",\r\n"
			+ "        \"partyReference\": \"C1EA9C65-CD0B-4534-8AF3-AC3A009190A0\"\r\n"
			+ "    }\r\n"
			+ "}";
	
	
	
	public static final String TESTPolicyHolderUpdate =
			"{\r\n"
			+ "    \"preferedCommunicationMethod\": \"None\",\r\n"
			+ "    \"addresses\": [\r\n"
			+ "        {\r\n"
			+ "            \"addressType\": \"Street\",\r\n"
			+ "            \"addressLine1\": \"21 Jump Street, Eikenhof, Johanneburg, Gauteng, 1818\",\r\n"
			+ "            \"addressLine2\": null,\r\n"
			+ "            \"addressLine3\": null,\r\n"
			+ "            \"suburb\": null,\r\n"
			+ "            \"townCity\": null,\r\n"
			+ "            \"provinceState\": null,\r\n"
			+ "            \"country\": \"None\",\r\n"
			+ "            \"postalZipCode\": null\r\n"
			+ "        }\r\n"
			+ "    ],\r\n"
			+ "    \"emailAddress\": \"postman@Gmail.Com\",\r\n"
			+ "    \"language\": \"None\",\r\n"
			+ "    \"marketingConsent\": null,\r\n"
			+ "    \"policyReplacement\": null,\r\n"
			+ "    \"employmentDetails\": null,\r\n"
			+ "    \"sourceOfIncome\": \"None\",\r\n"
			+ "    \"sourceOfIncomeOther\": null,\r\n"
			+ "    \"sourceOfWealth\": \"None\",\r\n"
			+ "    \"sourceOfWealthOther\": null,\r\n"
			+ "    \"countryOfResidence\": \"None\",\r\n"
			+ "    \"requirements\": [],\r\n"
			+ "    \"verifications\": [],\r\n"
			+ "    \"documents\": [],\r\n"
			+ "    \"title\": \"None\",\r\n"
			+ "    \"initials\": null,\r\n"
			+ "    \"firstNames\": \"ZENZI\",\r\n"
			+ "    \"surname\": \"DLANGAMANDLA\",\r\n"
			+ "    \"maidenName\": null,\r\n"
			+ "    \"gender\": \"None\",\r\n"
			+ "    \"birthDate\": \"1984-12-26T00:00:00+00:00\",\r\n"
			+ "    \"identities\": [\r\n"
			+ "        {\r\n"
			+ "            \"identityType\": \"NationalIdentityNumber\",\r\n"
			+ "            \"identityNumber\": \"8412260245088\",\r\n"
			+ "            \"issueCountry\": \"None\",\r\n"
			+ "            \"issueDate\": null,\r\n"
			+ "            \"expiryDate\": null,\r\n"
			+ "            \"citizenshipCountry\": \"SouthAfrica\"\r\n"
			+ "        }\r\n"
			+ "    ],\r\n"
			+ "    \"maritalStatus\": \"None\",\r\n"
			+ "    \"contactNumbers\": [\r\n"
			+ "        {\r\n"
			+ "            \"contactType\": \"Mobile\",\r\n"
			+ "            \"contactNumber\": \"0720720722\",\r\n"
			+ "            \"countryCode\": \"27\",\r\n"
			+ "            \"extension\": null\r\n"
			+ "        }\r\n"
			+ "    ],\r\n"
			+ "    \"partyType\": \"Person\",\r\n"
			+ "    \"rolePlayerType\": \"PolicyHolder\",\r\n"
			+ "    \"partyReference\": \"C1EA9C65-CD0B-4534-8AF3-AC3A009190A0\"\r\n"
			+ "}";
	
	public static final String NIFPolicyHolderUpdatepayload =
			"{\r\n"
			+ "    \"preferedCommunicationMethod\": \"None\",\r\n"
			+ "    \"addresses\": [\r\n"
			+ "        {\r\n"
			+ "            \"addressType\": \"Street\",\r\n"
			+ "            \"addressLine1\": \"21 Jump Street\",\r\n"
			+ "            \"addressLine2\": null,\r\n"
			+ "            \"addressLine3\": null,\r\n"
			+ "            \"suburb\": \"Eikenhof\",\r\n"
			+ "            \"townCity\": \"Johanneburg\",\r\n"
			+ "            \"provinceState\": \"Gauteng\",\r\n"
			+ "            \"country\": \"None\",\r\n"
			+ "            \"postalZipCode\": 1818\r\n"
			+ "        }\r\n"
			+ "    ],\r\n"
			+ "    \"emailAddress\": \"testman@gmail.com\",\r\n"
			+ "    \"language\": \"None\",\r\n"
			+ "    \"marketingConsent\": null,\r\n"
			+ "    \"policyReplacement\": null,\r\n"
			+ "    \"employmentDetails\": null,\r\n"
			+ "    \"sourceOfIncome\": \"None\",\r\n"
			+ "    \"sourceOfIncomeOther\": null,\r\n"
			+ "    \"sourceOfWealth\": \"None\",\r\n"
			+ "    \"sourceOfWealthOther\": null,\r\n"
			+ "    \"countryOfResidence\": \"None\",\r\n"
			+ "    \"requirements\": [],\r\n"
			+ "    \"verifications\": [],\r\n"
			+ "    \"documents\": [],\r\n"
			+ "    \"title\": \"Mr\",\r\n"
			+ "    \"initials\": null,\r\n"
			+ "    \"firstNames\": \"LUCKY HAMMILTON\",\r\n"
			+ "    \"surname\": \"KHUMBANe\",\r\n"
			+ "    \"maidenName\": null,\r\n"
			+ "    \"gender\": \"None\",\r\n"
			+ "    \"birthDate\": \"1978-08-28T00:00:00+00:00\",\r\n"
			+ "    \"identities\": [\r\n"
			+ "        {\r\n"
			+ "            \"identityType\": \"NationalIdentityNumber\",\r\n"
			+ "            \"identityNumber\": \"7808285908082\",\r\n"
			+ "            \"issueCountry\": \"None\",\r\n"
			+ "            \"issueDate\": null,\r\n"
			+ "            \"expiryDate\": null,\r\n"
			+ "            \"citizenshipCountry\": \"SouthAfrica\"\r\n"
			+ "        }\r\n"
			+ "    ],\r\n"
			+ "    \"maritalStatus\": \"None\",\r\n"
			+ "    \"contactNumbers\": [\r\n"
			+ "        {\r\n"
			+ "            \"contactType\": \"Mobile\",\r\n"
			+ "            \"contactNumber\": \"0720720000\",\r\n"
			+ "            \"countryCode\": \"27\",\r\n"
			+ "            \"extension\": null\r\n"
			+ "        }\r\n"
			+ "    ],\r\n"
			+ "    \"partyType\": \"Person\",\r\n"
			+ "    \"rolePlayerType\": \"PolicyHolder\",\r\n"
			+ "    \"partyReference\": \"1D9002C2-F682-4544-A2F5-AC5500E932CA\"\r\n"
			+ "}";
	
	
	public static final String UpdatePolicyHolderPayloads = 
			"{\r\n"
			+ "    \"$type\": \"PolicyHolder\",\r\n"
			+ "    \"preferedCommunicationMethod\": \"None\",\r\n"
			+ "    \"addresses\": [\r\n"
			+ "        {\r\n"
			+ "            \"$type\": \"Address\",\r\n"
			+ "            \"addressType\": \"Street\",\r\n"
			+ "            \"addressLine1\": \"21 Jump Street\",\r\n"
			+ "            \"addressLine2\": null,\r\n"
			+ "            \"addressLine3\": null,\r\n"
			+ "            \"suburb\": \"Eikenhof\",\r\n"
			+ "            \"townCity\": \"Johanneburg\",\r\n"
			+ "            \"provinceState\": \"Gauteng\",\r\n"
			+ "            \"country\": \"None\",\r\n"
			+ "            \"postalZipCode\": 1818\r\n"
			+ "        }\r\n"
			+ "    ],\r\n"
			+ "    \"emailAddress\": \"testman@gmail.com\",\r\n"
			+ "    \"language\": \"None\",\r\n"
			+ "    \"marketingConsent\": null,\r\n"
			+ "    \"policyReplacement\": null,\r\n"
			+ "    \"employmentDetails\": null,\r\n"
			+ "    \"sourceOfIncome\": \"None\",\r\n"
			+ "    \"sourceOfIncomeOther\": null,\r\n"
			+ "    \"sourceOfWealth\": \"None\",\r\n"
			+ "    \"sourceOfWealthOther\": null,\r\n"
			+ "    \"countryOfResidence\": \"None\",\r\n"
			+ "    \"requirements\": [],\r\n"
			+ "    \"verifications\": [],\r\n"
			+ "    \"documents\": [],\r\n"
			+ "    \"title\": \"None\",\r\n"
			+ "    \"initials\": null,\r\n"
			+ "    \"firstNames\": \"ZENZI\",\r\n"
			+ "    \"surname\": \"DLANGAMANDLA\",\r\n"
			+ "    \"maidenName\": null,\r\n"
			+ "    \"gender\": \"None\",\r\n"
			+ "    \"birthDate\": \"1984-12-26T00:00:00+00:00\",\r\n"
			+ "    \"identities\": [\r\n"
			+ "        {\r\n"
			+ "            \"identityType\": \"NationalIdentityNumber\",\r\n"
			+ "            \"identityNumber\": \"8412260245088\",\r\n"
			+ "            \"issueCountry\": \"None\",\r\n"
			+ "            \"issueDate\": null,\r\n"
			+ "            \"expiryDate\": null,\r\n"
			+ "            \"citizenshipCountry\": \"SouthAfrica\"\r\n"
			+ "        }\r\n"
			+ "    ],\r\n"
			+ "    \"maritalStatus\": \"None\",\r\n"
			+ "    \"contactNumbers\": [\r\n"
			+ "        {\r\n"
			+ "            \"contactType\": \"Mobile\",\r\n"
			+ "            \"contactNumber\": \"0720720000\",\r\n"
			+ "            \"countryCode\": \"27\",\r\n"
			+ "            \"extension\": null\r\n"
			+ "        }\r\n"
			+ "    ],\r\n"
			+ "    \"partyType\": \"Person\",\r\n"
			+ "    \"rolePlayerType\": \"PolicyHolder\",\r\n"
			+ "    \"partyReference\": \"C1EA9C65-CD0B-4534-8AF3-AC3A009190A0\"\r\n"
			+ "}";
	public static final String ChangeBeneficiariesPayload = 
			"\r\n"
			+ "{\r\n"
			+ "    \"personBeneficiaries\": [\r\n"
			+ "        {\r\n"
			+ "            \"$type\": \"Beneficiary\",\r\n"
			+ "            \"percentageShare\": 100,\r\n"
			+ "            \"title\": \"Mr\",\r\n"
			+ "            \"initials\": \"R\",\r\n"
			+ "            \"firstNames\": \"DANIEL\",\r\n"
			+ "            \"surname\": \"BENNETT\",\r\n"
			+ "            \"birthDate\": \"1989-11-11T00:00:00+00:00\",\r\n"
			+ "            \"identities\": [\r\n"
			+ "                {\r\n"
			+ "                    \"identityType\": \"NationalIdentityNumber\",\r\n"
			+ "                    \"identityNumber\": \"8911115071086\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"contactNumbers\": [\r\n"
			+ "                {\r\n"
			+ "                    \"contactType\": \"Mobile\",\r\n"
			+ "                    \"contactNumber\": \"0739455362\",\r\n"
			+ "                    \"countryCode\": \"27\"\r\n"
			+ "                }\r\n"
			+ "            ],\r\n"
			+ "            \"partyType\": \"Person\",\r\n"
			+ "            \"rolePlayerType\": \"Beneficiary\"\r\n"
			+ "        }\r\n"
			+ "    ]\r\n"
			+ "}\r\n"
			+ "";
	
	
	
	public static final String UploadDocument = "{\r\n"
			+ "  \"documentReference\": \"Postman1234SIT\",\r\n"
			+ "  \"documentName\": \"Application1234Postman\",\r\n"
			+ "  \"documentDescription\": \"This is a test via postman in SIT\",\r\n"
			+ "  \"documentFormat\": \"Html\",\r\n"
			+ "  \"documentType\": \"PolicyDocument\",\r\n"
			+ "  \"otherDocumentType\": null,\r\n"
			+ "  \"documentData\": \"JVBERi0xLjUKJeLjz9MKNSAwIG9iago8PC9GaWx0ZXIvRmxhdGVEZWNvZGUvTGVuZ3RoIDMzMDg+PnN0cmVhbQp4nL1cWY8bxxFugG/0g6XIsmVZAQhIWa2sFXd6+pih4adgd8mVNt57qYN6SGxLcBDZiAMkfz9V1XPUUGKzmsPEa5HTPUd1f3VX9/Cfwz9fDY0flZkfXf00PLwang/z0XPs1aMM\",\r\n"
			+ "  \"documentDate\": \"2021-05-12T09:01:24.809Z\"\r\n"
			+ "}";
			
}
